### ISSUE TITLE
Predicting centerlines using multi view images

### ISSUE THREAD

**Issue by shivakumar-tekumatla** [ybarancan/STSU#18]
Hi, 
Thanks for open-sourcing this amazing work. 
I was wondering if there is any way to use this code to fuse multiple views from NuScenes for predicting the centerlines. 
For example, right now I see that you are using CAM_FRONT for predicting all the centerlines. Can we add CAM_FRONT_LEFT, CAM_FRONT_RIGHT to widen the view and predict the centerlines?

**Comment by ybarancan** [comment]
Hi,
It can be easily extended. You need to change the make_nuscenes_label.py file to output not [-25,25,0,50] but [-50,50,-50,50]. This would give the local lane graph in 360 surrounding. Then, instead of feeding only front view images, you can feed all camera images to the backbone, concatenate the resulting representations in channel dimension and feed that to the transformer.

**Comment by shivakumar-tekumatla** [comment]
Thanks for the reply. 
Expanding on what you suggested, can we generate labels using `make_nuscenes_label.py` only for CAM_FRONT even if we are feeding multiple images? 
Essentially, in `dataset.py`( following screenshot), can we still use the labels that we get using `self.load_line_labels` generated for `CAM_FRONT` along with 360 image view?
<img width="912" alt="image" src="https://user-images.githubusercontent.com/55010991/234935580-2a255641-b5f9-4ed9-88d6-c5f9cf3e3ea3.png">

**Comment by ybarancan** [comment]
Yes. So after you generate labels with make_nuscenes_labels.py where in the config file you change the extents of the FOV, the rest of the code should be same. But I didn't try it. You might run into some small bugs but it shouldn't be hard to debug. We can discuss them if/when you encounter.

**Comment by shivakumar-tekumatla** [comment]
Hi 

I am unable to understand the difference between each of the following conditions, could you please help?

![image](https://user-images.githubusercontent.com/55010991/235307344-965b04d8-9e15-4e8c-b597-0db821331cd1.png)

Also, we are basically passing each image to the backbone and getting low-level features. after that should we concat like we are doing in lines 79,80, and 82 (see the below image) and then pass this concatenated vector to the transformer?

![image](https://user-images.githubusercontent.com/55010991/235307366-f33c8c49-4d5f-4078-963f-0ee256066220.png)

When I do this I get the following error.

```
 File "/home/Shiva/dl/STSU_old/src/detr/detr.py", line 261, in forward
    hs, trans_memory = self.transformer(self.input_proj(src), mask, selected_embed, torch.cat([pos[-1], bev_pos[-1]],dim=1))
  File "/home/Shiva/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/Shiva/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 465, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/Shiva/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 461, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [768, 256, 1, 1], expected input[1, 768, 28, 50] to have 256 channels, but got 768 channels instead
```

**Comment by ybarancan** [comment]
Yes, the code you give should work. The options in the first image are not important. You can delete the elif and else cases. Split is what we use anyways. The reason you got the error is either 1) self.input_proj is not defined properly for this new case or 2) the transformer hidden_dim is not defined properly. My suggestion is define self.input_proj as nn.conv2d(256*(n_cameras), 256) and feed out = torch.cat(out,dim=1) to that. So src = self.input_proj( torch.cat(out,dim=1) ) where hs, trans_memory = self.transformer(src, ...).

**Comment by ybarancan** [comment]
You can try to add one more conv layer where each image backbone feature is passed in batch dimension and then concatenated and then fed to input_proj. Something like:
all_feats = []
''for k in images:''
     temp, temp_pos = self.inter_conv(self.backbone(k))
    all_feats.append(temp)
''end for''
src=self.input_proj(torch.cat(all_feats, dim=1))
to_feed_pos = temp_pos
where self.inter_conv is a convolutional layer that you will define. Then you can feed the ''src'' matrix to transformer. Note that, the positional encoding you feed should match the src dimensions. Same also applies to the mask.

**Comment by shivakumar-tekumatla** [comment]
I made the suggested changes and it proceeded further. 
However, I disabled the zoom sampling, prediction of objects and object_refinement part. 
is it fine to do that? 
and I get detected nothing error 
is it because it's in initial epochs or because of some other flag?

![image](https://user-images.githubusercontent.com/55010991/235318967-ffcbc6a4-79b9-4ce5-a660-5ad760eeda98.png)

**Comment by shivakumar-tekumatla** [comment]
I made changes in positional encoding to incorporate multiple images. What I am doing is multiplying camera extrinsic parameters with homogeneous coordinates of x_embed and y_embed, and then the code runs as per what you did. But getting the following error after 2-3 epochs. Is this approach correct, and why is this error coming after a couple of epochs?
```
Traceback (most recent call last):
  File "/home/Shiva/dl/STSU_old/train_tr.py", line 847, in <module>
    main()
  File "/home/Shiva/dl/STSU_old/train_tr.py", line 812, in main
    val_con = evaluate(val_loader, model, criterion, postprocessors,val_confusion, config, args,thresh)
  File "/home/Shiva/dl/STSU_old/train_tr.py", line 309, in evaluate
    outputs = model(seq_images,cuda_targets[0]['calib'], targets[0]['left_traffic'])
  File "/home/Shiva/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/Shiva/dl/STSU_old/src/detr/detr.py", line 234, in forward
    features, low_features, pos, bev_pos = self.backbone(samples,calib_smallest, extrinsics, self.abs_bev)
  File "/home/Shiva/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/Shiva/dl/STSU_old/src/detr/deeplab_backbone.py", line 75, in forward
    pos.append(self[1](xs,calib, extrinsics[i], bev=True, abs_bev=abs_bev).to(xs.dtype))
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number
```

**Comment by ybarancan** [comment]
It seems like extrinsics is problematic. It might be because camera extrinsics are not returned properly from the dataloader due to some exception. Can you print extrinsics tensor? I think you don't need to make any changes to positional embedding. Instead you can maybe use CoordConv in self.inter_conv and self.input proj and possible add a few convolutions. Then the regular positional embedding should work fine. 
Another way is you don't concatenate the individual feature maps of different camera images in channel dimension but you concatenate them in batch dimension.  Let's say you have K images with HW feature map shapes and F channel dims. You concatenate them into KxFxHxW and then reshape it into KHW x 1 x F to feed the transformer. Then you can make changes to positional embeddings to each HW slice of the input. This will probably work better than the first method. The change you make can be really simple like setting apart a few dimensions of the pos embedding as indicator one hot variables to differentiate between cameras so if F =256 and K=3, pos embedding will be 253 dimensional and the remaining 3 dimensions will be one hot for each camera. Or you can go for a more complicated approach like 'Cross-view transformers for real-time map-view semantic segmentation'.
