### ISSUE TITLE
Dalaloader error segmentation fault core dumped

### ISSUE THREAD

**Issue by synsin0** [ybarancan/STSU#6]
I suspect it is a multi-processing thread error. If I turn num_workers in build_nuscenes_dataloader to be 0, there still exists an unknown segmentation fault.

Error info:
  Done reverse indexing in 3.6 seconds.
======
ERROR:root:N LINES IN boston-seaport 2846
ERROR:root:N LINES IN singapore-onenorth 2002
ERROR:root:N LINES IN singapore-queenstown 2083
ERROR:root:N LINES IN singapore-hollandvillage 1320
ERROR:root:N LINES IN boston-seaport 2846
ERROR:root:N LINES IN singapore-onenorth 2002
ERROR:root:N LINES IN singapore-queenstown 2083
ERROR:root:N LINES IN singapore-hollandvillage 1320
ERROR:root:MODEL FREEZE
ERROR:root:LOADED ./lanefinder/nuscenes_TR_True/transformer.pth
ERROR:root:LOADED MY
ERROR:root:LOADED MY CHECKPOINT
ERROR:root:MODEL FREEZE

=== Beginning epoch 128 of 200 ===
ERROR: Unexpected segmentation fault encountered in worker.
Traceback (most recent call last):
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/connection.py", line 921, in wait
    ready = selector.select(timeout)
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 2706) is killed by signal: Segmentation fault. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_tr.py", line 829, in <module>
    main()
  File "train_tr.py", line 783, in main
    iteration, confusion=train(train_loader, train_dataset,model, criterion, optimizer, refiner_optimizer, postprocessors ,confusion, config,args, iteration, transforms)
  File "train_tr.py", line 48, in train
    for i, batch in enumerate(dataloader):
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1152, in _get_data
    success, data = self._try_get_data()
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1003, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 2706) exited unexpectedly

Done reverse indexing in 3.6 seconds.
======
ERROR:root:N LINES IN boston-seaport 2846
ERROR:root:N LINES IN singapore-onenorth 2002
ERROR:root:N LINES IN singapore-queenstown 2083
ERROR:root:N LINES IN singapore-hollandvillage 1320
ERROR:root:N LINES IN boston-seaport 2846
ERROR:root:N LINES IN singapore-onenorth 2002
ERROR:root:N LINES IN singapore-queenstown 2083
ERROR:root:N LINES IN singapore-hollandvillage 1320
ERROR:root:MODEL FREEZE
ERROR:root:LOADED ./lanefinder/nuscenes_TR_True/transformer.pth
ERROR:root:LOADED MY
ERROR:root:LOADED MY CHECKPOINT
ERROR:root:MODEL FREEZE

=== Beginning epoch 128 of 200 ===
ERROR: Unexpected segmentation fault encountered in worker.
Traceback (most recent call last):
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/connection.py", line 921, in wait
    ready = selector.select(timeout)
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 2706) is killed by signal: Segmentation fault. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_tr.py", line 829, in <module>
    main()
  File "train_tr.py", line 783, in main
    iteration, confusion=train(train_loader, train_dataset,model, criterion, optimizer, refiner_optimizer, postprocessors ,confusion, config,args, iteration, transforms)
  File "train_tr.py", line 48, in train
    for i, batch in enumerate(dataloader):
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1152, in _get_data
    success, data = self._try_get_data()
  File "/home/yining/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1003, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 2706) exited unexpectedly

**Comment by ybarancan** [comment]
Segmentation fault error is very difficult to trace. Does it happen when you set the num_workers=1? And you can try using RandomSampler with option False to prevent threads trying to access to the same file at the same time.  Another possible problem is lack of enough CPU memory. You can try allocating more memory.
